export const GET_CLIENTS_ACTION = 'GET_CLIENTS';
export const ADD_CLIENT_ACTION = 'ADD_CLIENT';
export const SEND_MESSAGE_ACTION = 'SEND_MESSAGE';
export const FILTER_CLIENT_ACTION = 'FILTER_CLIENT';
export const GET_CLIENTBYID_ACTION = 'GET_CLIENTBYID';
export const SAVE_EDITION_ACTION = 'SAVE_EDITION';
export const DELETE_CLIENT_ACTION = 'DELETE_CLIENT';
